# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_animal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
